---

AllCops:
  Include:
    - 'Gemfile'
    - 'Rakefile'
  Exclude:
    - '**/*.lock'
    - 'vendor/**/*'

############################################
# Enable cops that are disabled by default #
############################################

Style/AutoResourceCleanup:
  Enabled: true

Style/CollectionMethods:
  Enabled: true

Style/Copyright:
  Enabled: true
  Notice: '^# Copyright \(c\) 2\d{3} .+$'

Style/Encoding:
  Enabled: true

Style/FirstArrayElementLineBreak:
  Enabled: true

Style/FirstHashElementLineBreak:
  Enabled: true

Style/FirstMethodArgumentLineBreak:
  Enabled: true

Style/FirstMethodParameterLineBreak:
  Enabled: true

Style/ImplicitRuntimeError:
  Enabled: true

Style/InlineComment:
  Enabled: true

Style/MethodCalledOnDoEndBlock:
  Enabled: true

Style/MultilineAssignmentLayout:
  Enabled: true

Style/OptionHash:
  Enabled: true

Style/Send:
  Enabled: true

Style/SpecialGlobalVars:
  Enabled: false

Style/StringMethods:
  Enabled: true

Style/SymbolArray:
  Enabled: true

############################################
# Disable cops that are enabled by default #
############################################

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

############################################
# Ensure cops that are disabled by default #
############################################

Style/DocumentationMethod:
  Enabled: false

Style/MissingElse:
  Enabled: false

